# Dolanan Data Part 3

## Import Library

In [1]:
import pandas as pd
import numpy as np

## Import Dataset

### Import Dataset dan Explore

In [2]:
!dir

 Volume in drive D is FullBuster Disk
 Volume Serial Number is 5A8A-9E1D

 Directory of D:\Job Dosen ITTelkom Surabaya\Prodi Sains Data\Event Sains Data\Dolanan Data

26/08/2021  17:08    <DIR>          .
26/08/2021  17:08    <DIR>          ..
26/08/2021  08:59    <DIR>          .ipynb_checkpoints
26/08/2021  13:55    <DIR>          Data
14/08/2021  22:40           237.701 Dolanan Data #1 - Pengenalan Dasar Python.jpeg
22/08/2021  10:44           365.132 Dolanan Data #2 - Pengolahan Data Sederhana dengan Python.jpeg
26/08/2021  17:08           494.778 Dolanan Data #3.ipynb
26/08/2021  14:53                 0 Dolanan Data #3.pptx
14/08/2021  17:13       247.618.200 Dolanan Data Part 1.mp4
22/08/2021  10:44       220.349.959 Dolanan Data Part 2.mp4
26/08/2021  13:25             1.403 kategori-komoditas-pasar-sederhana.csv
26/08/2021  09:16             5.797 pasar-sederhana-01-2020.csv
17/08/2021  16:09           286.511 Thumbnail Youtube Dolanan Data Part 1.png
26/08/2021  08:48           328.257 Thumbnail Youtube Dolanan Data Part 2.png
              10 File(s)    469.687.738 bytes
               4 Dir(s)  427.196.588.032 bytes free

In [3]:
df = pd.read_csv("pasar-sederhana-01-2020.csv")

In [4]:
pd.set_option("display.max_columns", None)

In [5]:
#df.head()

In [6]:
#df.tail()

In [7]:
df.shape

(35, 33)

In [8]:
df

,lokasi,nama_komoditas,2020-01-01,2020-01-02,2020-01-03,2020-01-04,2020-01-05,2020-01-06,2020-01-07,2020-01-08,2020-01-09,2020-01-10,2020-01-11,2020-01-12,2020-01-13,2020-01-14,2020-01-15,2020-01-16,2020-01-17,2020-01-18,2020-01-19,2020-01-20,2020-01-21,2020-01-22,2020-01-23,2020-01-24,2020-01-25,2020-01-26,2020-01-27,2020-01-28,2020-01-29,2020-01-30,2020-01-31
0,Pasar Sederhana,Beras Medium,0,11000,11000,0,0,11000,11000,0,11000,11000,0,0,0,0,11000,11000,11000,0,0,0,11000,11000,11000,11000,0,0,11000,11000,0,11000,0
1,Pasar Sederhana,Cabe Merah,0,45000,45000,0,0,40000,40000,0,40000,60000,0,0,0,0,70000,70000,70000,0,0,0,80000,80000,80000,70000,0,0,70000,80000,0,80000,0
2,Pasar Sederhana,Bawang Merah,0,40000,35000,0,0,32000,40000,0,40000,40000,0,0,0,0,30000,30000,28000,0,0,0,30000,30000,30000,28000,0,0,28000,30000,0,30000,0
3,Pasar Sederhana,Daging Ayam Ras,0,35000,34000,0,0,34000,34000,0,34000,34000,0,0,0,0,38000,35000,34000,0,0,0,32000,32000,32000,32000,0,0,32000,32000,0,32000,0
4,Pasar Sederhana,Telur Ayam Ras,0,25000,25000,0,0,25000,24000,0,24000,24000,0,0,0,0,24000,24000,24000,0,0,0,24000,24000,24000,44000,0,0,24000,24000,0,24000,0
5,Pasar Sederhana,Daging Sapi,0,110000,110000,0,0,110000,110000,0,110000,110000,0,0,0,0,110000,110000,110000,0,0,0,110000,110000,110000,110000,0,0,110000,110000,0,110000,0
6,Pasar Sederhana,Minyak Goreng,0,14000,14000,0,0,14000,14000,0,14000,14000,0,0,0,0,14000,14000,14000,0,0,0,14000,14000,14000,14000,0,0,14000,14000,0,14000,0
7,Pasar Sederhana,Gula Pasir,0,13000,13000,0,0,13000,13000,0,13000,13000,0,0,0,0,13000,13000,13000,0,0,0,13500,13000,13000,13000,0,0,13000,13000,0,13000,0
8,Pasar Sederhana,Kentang,0,15000,15000,0,0,15000,15000,0,15000,15000,0,0,0,0,15000,15000,15000,0,0,0,18000,18000,18000,17000,0,0,17000,18000,0,18000,0
9,Pasar Sederhana,Kedelai,0,12000,12000,0,0,12000,12000,0,12000,12000,0,0,0,0,12000,12000,12000,0,0,0,12000,12000,12000,12000,0,0,12000,12000,0,12000,0
10,Pasar Sederhana,Tepung Terigu,0,7500,7500,0,0,7500,7500,0,7500,7500,0,0,0,0,7500,7500,7500,0,0,0,7500,7500,7500,7500,0,0,7500,7500,0,7500,0
11,Pasar Sederhana,Bawang Putih,0,35000,0,0,0,32000,0,0,35000,40000,0,0,0,0,35000,35000,35000,0,0,0,35000,35000,35000,32000,0,0,32000,35000,0,35000,0
12,Pasar Sederhana,Cabe Keriting,0,48000,48000,0,0,50000,55000,0,55000,55000,0,0,0,0,55000,55000,60000,0,0,0,60000,60000,60000,50000,0,0,60000,60000,0,60000,0
13,Pasar Sederhana,Cabe Rawit,0,50000,40000,0,0,40000,60000,0,60000,60000,0,0,0,0,70000,70000,70000,0,0,0,100000,100000,100000,80000,0,0,80000,90000,0,90000,0
14,Pasar Sederhana,Kacang Tanah,0,30000,30000,0,0,26000,26000,0,26000,26000,0,0,0,0,26000,26000,30000,0,0,0,30000,30000,30000,30000,0,0,30000,30000,0,30000,0
15,Pasar Sederhana,Ubi Kayu,0,5000,5000,0,0,5000,5000,0,5000,5000,0,0,0,0,5000,5000,5000,0,0,0,5000,5000,5000,5000,0,0,5000,5000,0,5000,0
16,Pasar Sederhana,Ubi Jalar,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17,Pasar Sederhana,Jagung,0,12000,12000,0,0,12000,10000,0,10000,10000,0,0,0,0,10000,10000,10000,0,0,0,10000,10000,10000,10000,0,0,10000,10000,0,10000,0
18,Pasar Sederhana,Ikan Olahan,0,80000,80000,0,0,80000,80000,0,80000,80000,0,0,0,0,80000,80000,80000,0,0,0,80000,80000,80000,80000,0,0,80000,80000,0,80000,0
19,Pasar Sederhana,Beras Premium,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
20,Pasar Sederhana,Minyak Goreng Curah,0,12000,12000,0,0,12000,12000,0,12000,12000,0,0,0,0,12000,12000,12000,0,0,0,12000,12000,12000,12000,0,0,13000,13000,0,13000,0
21,Pasar Sederhana,Daging Ayam Kampung,0,75000,75000,0,0,75000,75000,0,75000,75000,0,0,0,0,75000,75000,75000,0,0,0,75000,75000,75000,75000,0,0,75000,75000,0,75000,0
22,Pasar Sederhana,Telur Ayam Kampung,0,44000,44000,0,0,44000,44000,0,44000,44000,0,0,0,0,44000,44000,44000,0,0,0,44000,44000,44000,44000,0,0,44000,44000,0,44000,0
23,Pasar Sederhana,Susu Kental Manis Merk Bendera,0,10000,10000,0,0,10000,10000,0,10000,10000,0,0,0,0,10000,10000,10000,0,0,0,10000,10000,10000,10000,0,0,10000,10000,0,10000,0
24,Pasar Sederhana,Susu Kental Manis Merk Indomilk,0,10000,10000,0,0,10000,10000,0,10000,10000,0,0,0,0,10000,10000,10000,0,0,0,10000,10000,10000,10000,0,0,10000,10000,0,10000,0
25,Pasar Sederhana,Garam Beryodium Bata,0,3500,3500,0,0,3500,3500,0,3500,3500,0,0,0,0,3500,3500,3500,0,0,0,3500,3500,3500,3500,0,0,3500,3500,0,3500,0
26,Pasar Sederhana,Garam Beryodium Halus,0,12000,12000,0,0,12000,12000,0,12000,12000,0,0,0,0,12000,12000,12000,0,0,0,12000,12000,12000,12000,0,0,12000,12000,0,12000,0
27,Pasar Sederhana,Tepung Terigu Cakra Kembar,0,8000,8000,0,0,8000,13000,0,8000,8000,0,0,0,0,8000,8000,8000,0,0,0,8000,8000,8000,8000,0,0,8000,8000,0,8000,0
28,Pasar Sederhana,Tepung Terigu Kunci,0,7000,7000,0,0,7000,7000,0,7000,7000,0,0,0,0,8000,7000,7000,0,0,0,7000,7000,7000,7000,0,0,7000,7000,0,7000,0
29,Pasar Sederhana,Mie Instan,0,2500,2500,0,0,2500,2500,0,2500,2500,0,0,0,0,2500,2500,2500,0,0,0,2500,2500,2500,2500,0,0,2500,2500,0,2500,0
30,Pasar Sederhana,Cabe Rawit Hijau,0,35000,28000,0,0,28000,35000,0,35000,50000,0,0,0,0,35000,35000,30000,0,0,0,30000,30000,30000,36000,0,0,36000,36000,0,36000,0
31,Pasar Sederhana,Kacang Hijau,0,22000,22000,0,0,24000,24000,0,24000,24000,0,0,0,0,24000,24000,24000,0,0,0,24000,24000,24000,24000,0,0,24000,24000,0,24000,0
32,Pasar Sederhana,Susu Bubuk Dancow,0,43700,43700,0,0,43700,43700,0,43700,43700,0,0,0,0,43700,43700,43700,0,0,0,43700,43700,43700,43700,0,0,43700,43700,0,43700,0
33,Pasar Sederhana,Susu Bubuk Indomilk,0,36100,36100,0,0,36100,36100,0,36100,36100,0,0,0,0,36100,36100,10000,0,0,0,10000,36100,36100,36100,0,0,36100,36100,0,36100,0
34,Pasar Sederhana,Ikan Kembung,0,45000,45000,0,0,45000,45000,0,45000,45000,0,0,0,0,45000,45000,45000,0,0,0,45000,45000,45000,45000,0,0,45000,45000,0,45000,0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 33 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   lokasi          35 non-null     object
 1   nama_komoditas  35 non-null     object
 2   2020-01-01      35 non-null     int64
 3   2020-01-02      35 non-null     int64
 4   2020-01-03      35 non-null     int64
 5   2020-01-04      35 non-null     int64
 6   2020-01-05      35 non-null     int64
 7   2020-01-06      35 non-null     int64
 8   2020-01-07      35 non-null     int64
 9   2020-01-08      35 non-null     int64
 10  2020-01-09      35 non-null     int64
 11  2020-01-10      35 non-null     int64
 12  2020-01-11      35 non-null     int64
 13  2020-01-12      35 non-null     int64
 14  2020-01-13      35 non-null     int64
 15  2020-01-14      35 non-null     int64
 16  2020-01-15      35 non-null     int64
 17  2020-01-16      35 non-null     int64
 18  2020-01-17      35 non-null     int64
 19  2020-01-18      35 non-null     int64
 20  2020-01-19      35 non-null     int64
 21  2020-01-20      35 non-null     int64
 22  2020-01-21      35 non-null     int64
 23  2020-01-22      35 non-null     int64
 24  2020-01-23      35 non-null     int64
 25  2020-01-24      35 non-null     int64
 26  2020-01-25      35 non-null     int64
 27  2020-01-26      35 non-null     int64
 28  2020-01-27      35 non-null     int64
 29  2020-01-28      35 non-null     int64
 30  2020-01-29      35 non-null     int64
 31  2020-01-30      35 non-null     int64
 32  2020-01-31      35 non-null     int64
dtypes: int64(31), object(2)
memory usage: 9.1+ KB

In [10]:
df.describe()

,2020-01-01,2020-01-02,2020-01-03,2020-01-04,2020-01-05,2020-01-06,2020-01-07,2020-01-08,2020-01-09,2020-01-10,2020-01-11,2020-01-12,2020-01-13,2020-01-14,2020-01-15,2020-01-16,2020-01-17,2020-01-18,2020-01-19,2020-01-20,2020-01-21,2020-01-22,2020-01-23,2020-01-24,2020-01-25,2020-01-26,2020-01-27,2020-01-28,2020-01-29,2020-01-30,2020-01-31
count,35.0,35.000000,35.000000,35.0,35.0,35.000000,35.000000,35.0,35.000000,35.000000,35.0,35.0,35.0,35.0,35.000000,35.000000,35.000000,35.0,35.0,35.0,35.000000,35.000000,35.000000,35.000000,35.0,35.0,35.000000,35.000000,35.0,35.000000,35.0
mean,0.0,27237.142857,25580.000000,0.0,0.0,26265.714286,26551.428571,0.0,27408.571429,28551.428571,0.0,0.0,0.0,0.0,28408.571429,28294.285714,27577.142857,0.0,0.0,0.0,28820.000000,29551.428571,29551.428571,28980.000000,0.0,0.0,28722.857143,29465.714286,0.0,29465.714286,0.0
std,0.0,24939.032550,24970.497887,0.0,0.0,24505.448888,25678.674735,0.0,25391.410908,26196.209553,0.0,0.0,0.0,0.0,26662.381203,26658.415986,26926.360206,0.0,0.0,0.0,29151.710675,28997.772444,28997.772444,27096.904533,0.0,0.0,27250.775334,28329.811183,0.0,28329.811183,0.0
min,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0
25%,0.0,10000.000000,9000.000000,0.0,0.0,10000.000000,10000.000000,0.0,10000.000000,10000.000000,0.0,0.0,0.0,0.0,10000.000000,10000.000000,10000.000000,0.0,0.0,0.0,10000.000000,10000.000000,10000.000000,10000.000000,0.0,0.0,10000.000000,10000.000000,0.0,10000.000000,0.0
50%,0.0,15000.000000,14000.000000,0.0,0.0,15000.000000,14000.000000,0.0,15000.000000,15000.000000,0.0,0.0,0.0,0.0,15000.000000,15000.000000,14000.000000,0.0,0.0,0.0,14000.000000,18000.000000,18000.000000,17000.000000,0.0,0.0,17000.000000,18000.000000,0.0,18000.000000,0.0
75%,0.0,41850.000000,38050.000000,0.0,0.0,38050.000000,40000.000000,0.0,40000.000000,43850.000000,0.0,0.0,0.0,0.0,40850.000000,39900.000000,39350.000000,0.0,0.0,0.0,39350.000000,39900.000000,39900.000000,43850.000000,0.0,0.0,39900.000000,39900.000000,0.0,39900.000000,0.0
max,0.0,110000.000000,110000.000000,0.0,0.0,110000.000000,110000.000000,0.0,110000.000000,110000.000000,0.0,0.0,0.0,0.0,110000.000000,110000.000000,110000.000000,0.0,0.0,0.0,110000.000000,110000.000000,110000.000000,110000.000000,0.0,0.0,110000.000000,110000.000000,0.0,110000.000000,0.0

### Mengganti data dengan nilai 0 jadi cell kosong

In [11]:
# Replace zero values with NaN
df.replace(0, np.nan, inplace = True)

In [12]:
df

,lokasi,nama_komoditas,2020-01-01,2020-01-02,2020-01-03,2020-01-04,2020-01-05,2020-01-06,2020-01-07,2020-01-08,2020-01-09,2020-01-10,2020-01-11,2020-01-12,2020-01-13,2020-01-14,2020-01-15,2020-01-16,2020-01-17,2020-01-18,2020-01-19,2020-01-20,2020-01-21,2020-01-22,2020-01-23,2020-01-24,2020-01-25,2020-01-26,2020-01-27,2020-01-28,2020-01-29,2020-01-30,2020-01-31
0,Pasar Sederhana,Beras Medium,NaN,11000.0,11000.0,NaN,NaN,11000.0,11000.0,NaN,11000.0,11000.0,NaN,NaN,NaN,NaN,11000.0,11000.0,11000.0,NaN,NaN,NaN,11000.0,11000.0,11000.0,11000.0,NaN,NaN,11000.0,11000.0,NaN,11000.0,NaN
1,Pasar Sederhana,Cabe Merah,NaN,45000.0,45000.0,NaN,NaN,40000.0,40000.0,NaN,40000.0,60000.0,NaN,NaN,NaN,NaN,70000.0,70000.0,70000.0,NaN,NaN,NaN,80000.0,80000.0,80000.0,70000.0,NaN,NaN,70000.0,80000.0,NaN,80000.0,NaN
2,Pasar Sederhana,Bawang Merah,NaN,40000.0,35000.0,NaN,NaN,32000.0,40000.0,NaN,40000.0,40000.0,NaN,NaN,NaN,NaN,30000.0,30000.0,28000.0,NaN,NaN,NaN,30000.0,30000.0,30000.0,28000.0,NaN,NaN,28000.0,30000.0,NaN,30000.0,NaN
3,Pasar Sederhana,Daging Ayam Ras,NaN,35000.0,34000.0,NaN,NaN,34000.0,34000.0,NaN,34000.0,34000.0,NaN,NaN,NaN,NaN,38000.0,35000.0,34000.0,NaN,NaN,NaN,32000.0,32000.0,32000.0,32000.0,NaN,NaN,32000.0,32000.0,NaN,32000.0,NaN
4,Pasar Sederhana,Telur Ayam Ras,NaN,25000.0,25000.0,NaN,NaN,25000.0,24000.0,NaN,24000.0,24000.0,NaN,NaN,NaN,NaN,24000.0,24000.0,24000.0,NaN,NaN,NaN,24000.0,24000.0,24000.0,44000.0,NaN,NaN,24000.0,24000.0,NaN,24000.0,NaN
5,Pasar Sederhana,Daging Sapi,NaN,110000.0,110000.0,NaN,NaN,110000.0,110000.0,NaN,110000.0,110000.0,NaN,NaN,NaN,NaN,110000.0,110000.0,110000.0,NaN,NaN,NaN,110000.0,110000.0,110000.0,110000.0,NaN,NaN,110000.0,110000.0,NaN,110000.0,NaN
6,Pasar Sederhana,Minyak Goreng,NaN,14000.0,14000.0,NaN,NaN,14000.0,14000.0,NaN,14000.0,14000.0,NaN,NaN,NaN,NaN,14000.0,14000.0,14000.0,NaN,NaN,NaN,14000.0,14000.0,14000.0,14000.0,NaN,NaN,14000.0,14000.0,NaN,14000.0,NaN
7,Pasar Sederhana,Gula Pasir,NaN,13000.0,13000.0,NaN,NaN,13000.0,13000.0,NaN,13000.0,13000.0,NaN,NaN,NaN,NaN,13000.0,13000.0,13000.0,NaN,NaN,NaN,13500.0,13000.0,13000.0,13000.0,NaN,NaN,13000.0,13000.0,NaN,13000.0,NaN
8,Pasar Sederhana,Kentang,NaN,15000.0,15000.0,NaN,NaN,15000.0,15000.0,NaN,15000.0,15000.0,NaN,NaN,NaN,NaN,15000.0,15000.0,15000.0,NaN,NaN,NaN,18000.0,18000.0,18000.0,17000.0,NaN,NaN,17000.0,18000.0,NaN,18000.0,NaN
9,Pasar Sederhana,Kedelai,NaN,12000.0,12000.0,NaN,NaN,12000.0,12000.0,NaN,12000.0,12000.0,NaN,NaN,NaN,NaN,12000.0,12000.0,12000.0,NaN,NaN,NaN,12000.0,12000.0,12000.0,12000.0,NaN,NaN,12000.0,12000.0,NaN,12000.0,NaN
10,Pasar Sederhana,Tepung Terigu,NaN,7500.0,7500.0,NaN,NaN,7500.0,7500.0,NaN,7500.0,7500.0,NaN,NaN,NaN,NaN,7500.0,7500.0,7500.0,NaN,NaN,NaN,7500.0,7500.0,7500.0,7500.0,NaN,NaN,7500.0,7500.0,NaN,7500.0,NaN
11,Pasar Sederhana,Bawang Putih,NaN,35000.0,NaN,NaN,NaN,32000.0,NaN,NaN,35000.0,40000.0,NaN,NaN,NaN,NaN,35000.0,35000.0,35000.0,NaN,NaN,NaN,35000.0,35000.0,35000.0,32000.0,NaN,NaN,32000.0,35000.0,NaN,35000.0,NaN
12,Pasar Sederhana,Cabe Keriting,NaN,48000.0,48000.0,NaN,NaN,50000.0,55000.0,NaN,55000.0,55000.0,NaN,NaN,NaN,NaN,55000.0,55000.0,60000.0,NaN,NaN,NaN,60000.0,60000.0,60000.0,50000.0,NaN,NaN,60000.0,60000.0,NaN,60000.0,NaN
13,Pasar Sederhana,Cabe Rawit,NaN,50000.0,40000.0,NaN,NaN,40000.0,60000.0,NaN,60000.0,60000.0,NaN,NaN,NaN,NaN,70000.0,70000.0,70000.0,NaN,NaN,NaN,100000.0,100000.0,100000.0,80000.0,NaN,NaN,80000.0,90000.0,NaN,90000.0,NaN
14,Pasar Sederhana,Kacang Tanah,NaN,30000.0,30000.0,NaN,NaN,26000.0,26000.0,NaN,26000.0,26000.0,NaN,NaN,NaN,NaN,26000.0,26000.0,30000.0,NaN,NaN,NaN,30000.0,30000.0,30000.0,30000.0,NaN,NaN,30000.0,30000.0,NaN,30000.0,NaN
15,Pasar Sederhana,Ubi Kayu,NaN,5000.0,5000.0,NaN,NaN,5000.0,5000.0,NaN,5000.0,5000.0,NaN,NaN,NaN,NaN,5000.0,5000.0,5000.0,NaN,NaN,NaN,5000.0,5000.0,5000.0,5000.0,NaN,NaN,5000.0,5000.0,NaN,5000.0,NaN
16,Pasar Sederhana,Ubi Jalar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Pasar Sederhana,Jagung,NaN,12000.0,12000.0,NaN,NaN,12000.0,10000.0,NaN,10000.0,10000.0,NaN,NaN,NaN,NaN,10000.0,10000.0,10000.0,NaN,NaN,NaN,10000.0,10000.0,10000.0,10000.0,NaN,NaN,10000.0,10000.0,NaN,10000.0,NaN
18,Pasar Sederhana,Ikan Olahan,NaN,80000.0,80000.0,NaN,NaN,80000.0,80000.0,NaN,80000.0,80000.0,NaN,NaN,NaN,NaN,80000.0,80000.0,80000.0,NaN,NaN,NaN,80000.0,80000.0,80000.0,80000.0,NaN,NaN,80000.0,80000.0,NaN,80000.0,NaN
19,Pasar Sederhana,Beras Premium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Pasar Sederhana,Minyak Goreng Curah,NaN,12000.0,12000.0,NaN,NaN,12000.0,12000.0,NaN,12000.0,12000.0,NaN,NaN,NaN,NaN,12000.0,12000.0,12000.0,NaN,NaN,NaN,12000.0,12000.0,12000.0,12000.0,NaN,NaN,13000.0,13000.0,NaN,13000.0,NaN
21,Pasar Sederhana,Daging Ayam Kampung,NaN,75000.0,75000.0,NaN,NaN,75000.0,75000.0,NaN,75000.0,75000.0,NaN,NaN,NaN,NaN,75000.0,75000.0,75000.0,NaN,NaN,NaN,75000.0,75000.0,75000.0,75000.0,NaN,NaN,75000.0,75000.0,NaN,75000.0,NaN
22,Pasar Sederhana,Telur Ayam Kampung,NaN,44000.0,44000.0,NaN,NaN,44000.0,44000.0,NaN,44000.0,44000.0,NaN,NaN,NaN,NaN,44000.0,44000.0,44000.0,NaN,NaN,NaN,44000.0,44000.0,44000.0,44000.0,NaN,NaN,44000.0,44000.0,NaN,44000.0,NaN
23,Pasar Sederhana,Susu Kental Manis Merk Bendera,NaN,10000.0,10000.0,NaN,NaN,10000.0,10000.0,NaN,10000.0,10000.0,NaN,NaN,NaN,NaN,10000.0,10000.0,10000.0,NaN,NaN,NaN,10000.0,10000.0,10000.0,10000.0,NaN,NaN,10000.0,10000.0,NaN,10000.0,NaN
24,Pasar Sederhana,Susu Kental Manis Merk Indomilk,NaN,10000.0,10000.0,NaN,NaN,10000.0,10000.0,NaN,10000.0,10000.0,NaN,NaN,NaN,NaN,10000.0,10000.0,10000.0,NaN,NaN,NaN,10000.0,10000.0,10000.0,10000.0,NaN,NaN,10000.0,10000.0,NaN,10000.0,NaN
25,Pasar Sederhana,Garam Beryodium Bata,NaN,3500.0,3500.0,NaN,NaN,3500.0,3500.0,NaN,3500.0,3500.0,NaN,NaN,NaN,NaN,3500.0,3500.0,3500.0,NaN,NaN,NaN,3500.0,3500.0,3500.0,3500.0,NaN,NaN,3500.0,3500.0,NaN,3500.0,NaN
26,Pasar Sederhana,Garam Beryodium Halus,NaN,12000.0,12000.0,NaN,NaN,12000.0,12000.0,NaN,12000.0,12000.0,NaN,NaN,NaN,NaN,12000.0,12000.0,12000.0,NaN,NaN,NaN,12000.0,12000.0,12000.0,12000.0,NaN,NaN,12000.0,12000.0,NaN,12000.0,NaN
27,Pasar Sederhana,Tepung Terigu Cakra Kembar,NaN,8000.0,8000.0,NaN,NaN,8000.0,13000.0,NaN,8000.0,8000.0,NaN,NaN,NaN,NaN,8000.0,8000.0,8000.0,NaN,NaN,NaN,8000.0,8000.0,8000.0,8000.0,NaN,NaN,8000.0,8000.0,NaN,8000.0,NaN
28,Pasar Sederhana,Tepung Terigu Kunci,NaN,7000.0,7000.0,NaN,NaN,7000.0,7000.0,NaN,7000.0,7000.0,NaN,NaN,NaN,NaN,8000.0,7000.0,7000.0,NaN,NaN,NaN,7000.0,7000.0,7000.0,7000.0,NaN,NaN,7000.0,7000.0,NaN,7000.0,NaN
29,Pasar Sederhana,Mie Instan,NaN,2500.0,2500.0,NaN,NaN,2500.0,2500.0,NaN,2500.0,2500.0,NaN,NaN,NaN,NaN,2500.0,2500.0,2500.0,NaN,NaN,NaN,2500.0,2500.0,2500.0,2500.0,NaN,NaN,2500.0,2500.0,NaN,2500.0,NaN
30,Pasar Sederhana,Cabe Rawit Hijau,NaN,35000.0,28000.0,NaN,NaN,28000.0,35000.0,NaN,35000.0,50000.0,NaN,NaN,NaN,NaN,35000.0,35000.0,30000.0,NaN,NaN,NaN,30000.0,30000.0,30000.0,36000.0,NaN,NaN,36000.0,36000.0,NaN,36000.0,NaN
31,Pasar Sederhana,Kacang Hijau,NaN,22000.0,22000.0,NaN,NaN,24000.0,24000.0,NaN,24000.0,24000.0,NaN,NaN,NaN,NaN,24000.0,24000.0,24000.0,NaN,NaN,NaN,24000.0,24000.0,24000.0,24000.0,NaN,NaN,24000.0,24000.0,NaN,24000.0,NaN
32,Pasar Sederhana,Susu Bubuk Dancow,NaN,43700.0,43700.0,NaN,NaN,43700.0,43700.0,NaN,43700.0,43700.0,NaN,NaN,NaN,NaN,43700.0,43700.0,43700.0,NaN,NaN,NaN,43700.0,43700.0,43700.0,43700.0,NaN,NaN,43700.0,43700.0,NaN,43700.0,NaN
33,Pasar Sederhana,Susu Bubuk Indomilk,NaN,36100.0,36100.0,NaN,NaN,36100.0,36100.0,NaN,36100.0,36100.0,NaN,NaN,NaN,NaN,36100.0,36100.0,10000.0,NaN,NaN,NaN,10000.0,36100.0,36100.0,36100.0,NaN,NaN,36100.0,36100.0,NaN,36100.0,NaN
34,Pasar Sederhana,Ikan Kembung,NaN,45000.0,45000.0,NaN,NaN,45000.0,45000.0,NaN,45000.0,45000.0,NaN,NaN,NaN,NaN,45000.0,45000.0,45000.0,NaN,NaN,NaN,45000.0,45000.0,45000.0,45000.0,NaN,NaN,45000.0,45000.0,NaN,45000.0,NaN

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 33 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   lokasi          35 non-null     object
 1   nama_komoditas  35 non-null     object
 2   2020-01-01      0 non-null      float64
 3   2020-01-02      33 non-null     float64
 4   2020-01-03      32 non-null     float64
 5   2020-01-04      0 non-null      float64
 6   2020-01-05      0 non-null      float64
 7   2020-01-06      33 non-null     float64
 8   2020-01-07      32 non-null     float64
 9   2020-01-08      0 non-null      float64
 10  2020-01-09      33 non-null     float64
 11  2020-01-10      33 non-null     float64
 12  2020-01-11      0 non-null      float64
 13  2020-01-12      0 non-null      float64
 14  2020-01-13      0 non-null      float64
 15  2020-01-14      0 non-null      float64
 16  2020-01-15      33 non-null     float64
 17  2020-01-16      33 non-null     float64
 18  2020-01-17      33 non-null     float64
 19  2020-01-18      0 non-null      float64
 20  2020-01-19      0 non-null      float64
 21  2020-01-20      0 non-null      float64
 22  2020-01-21      33 non-null     float64
 23  2020-01-22      33 non-null     float64
 24  2020-01-23      33 non-null     float64
 25  2020-01-24      33 non-null     float64
 26  2020-01-25      0 non-null      float64
 27  2020-01-26      0 non-null      float64
 28  2020-01-27      33 non-null     float64
 29  2020-01-28      33 non-null     float64
 30  2020-01-29      0 non-null      float64
 31  2020-01-30      33 non-null     float64
 32  2020-01-31      0 non-null      float64
dtypes: float64(31), object(2)
memory usage: 9.1+ KB

In [14]:
df.describe()

,2020-01-01,2020-01-02,2020-01-03,2020-01-04,2020-01-05,2020-01-06,2020-01-07,2020-01-08,2020-01-09,2020-01-10,2020-01-11,2020-01-12,2020-01-13,2020-01-14,2020-01-15,2020-01-16,2020-01-17,2020-01-18,2020-01-19,2020-01-20,2020-01-21,2020-01-22,2020-01-23,2020-01-24,2020-01-25,2020-01-26,2020-01-27,2020-01-28,2020-01-29,2020-01-30,2020-01-31
count,0.0,33.000000,32.000000,0.0,0.0,33.000000,32.0000,0.0,33.000000,33.000000,0.0,0.0,0.0,0.0,33.000000,33.000000,33.000000,0.0,0.0,0.0,33.000000,33.000000,33.000000,33.000000,0.0,0.0,33.000000,33.000000,0.0,33.000000,0.0
mean,NaN,28887.878788,27978.125000,NaN,NaN,27857.575758,29040.6250,NaN,29069.696970,30281.818182,NaN,NaN,NaN,NaN,30130.303030,30009.090909,29248.484848,NaN,NaN,NaN,30566.666667,31342.424242,31342.424242,30736.363636,NaN,NaN,30463.636364,31251.515152,NaN,31251.515152,NaN
std,NaN,24731.580994,24791.280132,NaN,NaN,24337.587061,25467.3714,NaN,25203.601985,25982.583765,NaN,NaN,NaN,NaN,26491.796901,26495.664311,26831.536031,NaN,NaN,NaN,29118.343302,28905.655051,28905.655051,26915.815729,NaN,NaN,27098.521848,28199.048313,NaN,28199.048313,NaN
min,NaN,2500.000000,2500.000000,NaN,NaN,2500.000000,2500.0000,NaN,2500.000000,2500.000000,NaN,NaN,NaN,NaN,2500.000000,2500.000000,2500.000000,NaN,NaN,NaN,2500.000000,2500.000000,2500.000000,2500.000000,NaN,NaN,2500.000000,2500.000000,NaN,2500.000000,NaN
25%,NaN,11000.000000,10750.000000,NaN,NaN,11000.000000,10750.0000,NaN,10000.000000,10000.000000,NaN,NaN,NaN,NaN,10000.000000,10000.000000,10000.000000,NaN,NaN,NaN,10000.000000,10000.000000,10000.000000,10000.000000,NaN,NaN,10000.000000,10000.000000,NaN,10000.000000,NaN
50%,NaN,22000.000000,18500.000000,NaN,NaN,24000.000000,19500.0000,NaN,24000.000000,24000.000000,NaN,NaN,NaN,NaN,24000.000000,24000.000000,15000.000000,NaN,NaN,NaN,18000.000000,24000.000000,24000.000000,24000.000000,NaN,NaN,24000.000000,24000.000000,NaN,24000.000000,NaN
75%,NaN,43700.000000,40925.000000,NaN,NaN,40000.000000,40925.0000,NaN,40000.000000,44000.000000,NaN,NaN,NaN,NaN,43700.000000,43700.000000,43700.000000,NaN,NaN,NaN,43700.000000,43700.000000,43700.000000,44000.000000,NaN,NaN,43700.000000,43700.000000,NaN,43700.000000,NaN
max,NaN,110000.000000,110000.000000,NaN,NaN,110000.000000,110000.0000,NaN,110000.000000,110000.000000,NaN,NaN,NaN,NaN,110000.000000,110000.000000,110000.000000,NaN,NaN,NaN,110000.000000,110000.000000,110000.000000,110000.000000,NaN,NaN,110000.000000,110000.000000,NaN,110000.000000,NaN

## Memeriksa Missing Value pada Dataset

### Memeriksa Missing Value pada Baris Mana

In [15]:
df.shape

(35, 33)

In [16]:
df.isnull().sum()

lokasi             0
nama_komoditas     0
2020-01-01        35
2020-01-02         2
2020-01-03         3
2020-01-04        35
2020-01-05        35
2020-01-06         2
2020-01-07         3
2020-01-08        35
2020-01-09         2
2020-01-10         2
2020-01-11        35
2020-01-12        35
2020-01-13        35
2020-01-14        35
2020-01-15         2
2020-01-16         2
2020-01-17         2
2020-01-18        35
2020-01-19        35
2020-01-20        35
2020-01-21         2
2020-01-22         2
2020-01-23         2
2020-01-24         2
2020-01-25        35
2020-01-26        35
2020-01-27         2
2020-01-28         2
2020-01-29        35
2020-01-30         2
2020-01-31        35
dtype: int64

In [17]:
df.isnull().sum(axis = 1)

0     15
1     15
2     15
3     15
4     15
5     15
6     15
7     15
8     15
9     15
10    15
11    17
12    15
13    15
14    15
15    15
16    31
17    15
18    15
19    31
20    15
21    15
22    15
23    15
24    15
25    15
26    15
27    15
28    15
29    15
30    15
31    15
32    15
33    15
34    15
dtype: int64

In [18]:
df.isnull().sum(axis = 1)==31

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16     True
17    False
18    False
19     True
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
dtype: bool

In [19]:
(df.isnull().sum(axis = 1)==31).sum()

2

In [20]:
df.iloc[[16, 19], :]

,lokasi,nama_komoditas,2020-01-01,2020-01-02,2020-01-03,2020-01-04,2020-01-05,2020-01-06,2020-01-07,2020-01-08,2020-01-09,2020-01-10,2020-01-11,2020-01-12,2020-01-13,2020-01-14,2020-01-15,2020-01-16,2020-01-17,2020-01-18,2020-01-19,2020-01-20,2020-01-21,2020-01-22,2020-01-23,2020-01-24,2020-01-25,2020-01-26,2020-01-27,2020-01-28,2020-01-29,2020-01-30,2020-01-31
16,Pasar Sederhana,Ubi Jalar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Pasar Sederhana,Beras Premium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
# Drop 16 and 19 row
df.drop([16, 19], axis = 0, inplace = True)

In [22]:
df.shape

(33, 33)

### Memeriksa Missing Value pada Kolom Mana

In [23]:
df.isnull().sum()

lokasi             0
nama_komoditas     0
2020-01-01        33
2020-01-02         0
2020-01-03         1
2020-01-04        33
2020-01-05        33
2020-01-06         0
2020-01-07         1
2020-01-08        33
2020-01-09         0
2020-01-10         0
2020-01-11        33
2020-01-12        33
2020-01-13        33
2020-01-14        33
2020-01-15         0
2020-01-16         0
2020-01-17         0
2020-01-18        33
2020-01-19        33
2020-01-20        33
2020-01-21         0
2020-01-22         0
2020-01-23         0
2020-01-24         0
2020-01-25        33
2020-01-26        33
2020-01-27         0
2020-01-28         0
2020-01-29        33
2020-01-30         0
2020-01-31        33
dtype: int64

In [24]:
df.isnull().sum()==33

lokasi            False
nama_komoditas    False
2020-01-01         True
2020-01-02        False
2020-01-03        False
2020-01-04         True
2020-01-05         True
2020-01-06        False
2020-01-07        False
2020-01-08         True
2020-01-09        False
2020-01-10        False
2020-01-11         True
2020-01-12         True
2020-01-13         True
2020-01-14         True
2020-01-15        False
2020-01-16        False
2020-01-17        False
2020-01-18         True
2020-01-19         True
2020-01-20         True
2020-01-21        False
2020-01-22        False
2020-01-23        False
2020-01-24        False
2020-01-25         True
2020-01-26         True
2020-01-27        False
2020-01-28        False
2020-01-29         True
2020-01-30        False
2020-01-31         True
dtype: bool

In [25]:
(df.isnull().sum()==33).sum()

15

In [26]:
df.head()

,lokasi,nama_komoditas,2020-01-01,2020-01-02,2020-01-03,2020-01-04,2020-01-05,2020-01-06,2020-01-07,2020-01-08,2020-01-09,2020-01-10,2020-01-11,2020-01-12,2020-01-13,2020-01-14,2020-01-15,2020-01-16,2020-01-17,2020-01-18,2020-01-19,2020-01-20,2020-01-21,2020-01-22,2020-01-23,2020-01-24,2020-01-25,2020-01-26,2020-01-27,2020-01-28,2020-01-29,2020-01-30,2020-01-31
0,Pasar Sederhana,Beras Medium,NaN,11000.0,11000.0,NaN,NaN,11000.0,11000.0,NaN,11000.0,11000.0,NaN,NaN,NaN,NaN,11000.0,11000.0,11000.0,NaN,NaN,NaN,11000.0,11000.0,11000.0,11000.0,NaN,NaN,11000.0,11000.0,NaN,11000.0,NaN
1,Pasar Sederhana,Cabe Merah,NaN,45000.0,45000.0,NaN,NaN,40000.0,40000.0,NaN,40000.0,60000.0,NaN,NaN,NaN,NaN,70000.0,70000.0,70000.0,NaN,NaN,NaN,80000.0,80000.0,80000.0,70000.0,NaN,NaN,70000.0,80000.0,NaN,80000.0,NaN
2,Pasar Sederhana,Bawang Merah,NaN,40000.0,35000.0,NaN,NaN,32000.0,40000.0,NaN,40000.0,40000.0,NaN,NaN,NaN,NaN,30000.0,30000.0,28000.0,NaN,NaN,NaN,30000.0,30000.0,30000.0,28000.0,NaN,NaN,28000.0,30000.0,NaN,30000.0,NaN
3,Pasar Sederhana,Daging Ayam Ras,NaN,35000.0,34000.0,NaN,NaN,34000.0,34000.0,NaN,34000.0,34000.0,NaN,NaN,NaN,NaN,38000.0,35000.0,34000.0,NaN,NaN,NaN,32000.0,32000.0,32000.0,32000.0,NaN,NaN,32000.0,32000.0,NaN,32000.0,NaN
4,Pasar Sederhana,Telur Ayam Ras,NaN,25000.0,25000.0,NaN,NaN,25000.0,24000.0,NaN,24000.0,24000.0,NaN,NaN,NaN,NaN,24000.0,24000.0,24000.0,NaN,NaN,NaN,24000.0,24000.0,24000.0,44000.0,NaN,NaN,24000.0,24000.0,NaN,24000.0,NaN

In [27]:
df.iloc[:, [0, 1, 2, 5, 6, 9]]

,lokasi,nama_komoditas,2020-01-01,2020-01-04,2020-01-05,2020-01-08
0,Pasar Sederhana,Beras Medium,NaN,NaN,NaN,NaN
1,Pasar Sederhana,Cabe Merah,NaN,NaN,NaN,NaN
2,Pasar Sederhana,Bawang Merah,NaN,NaN,NaN,NaN
3,Pasar Sederhana,Daging Ayam Ras,NaN,NaN,NaN,NaN
4,Pasar Sederhana,Telur Ayam Ras,NaN,NaN,NaN,NaN
5,Pasar Sederhana,Daging Sapi,NaN,NaN,NaN,NaN
6,Pasar Sederhana,Minyak Goreng,NaN,NaN,NaN,NaN
7,Pasar Sederhana,Gula Pasir,NaN,NaN,NaN,NaN
8,Pasar Sederhana,Kentang,NaN,NaN,NaN,NaN
9,Pasar Sederhana,Kedelai,NaN,NaN,NaN,NaN
10,Pasar Sederhana,Tepung Terigu,NaN,NaN,NaN,NaN
11,Pasar Sederhana,Bawang Putih,NaN,NaN,NaN,NaN
12,Pasar Sederhana,Cabe Keriting,NaN,NaN,NaN,NaN
13,Pasar Sederhana,Cabe Rawit,NaN,NaN,NaN,NaN
14,Pasar Sederhana,Kacang Tanah,NaN,NaN,NaN,NaN
15,Pasar Sederhana,Ubi Kayu,NaN,NaN,NaN,NaN
17,Pasar Sederhana,Jagung,NaN,NaN,NaN,NaN
18,Pasar Sederhana,Ikan Olahan,NaN,NaN,NaN,NaN
20,Pasar Sederhana,Minyak Goreng Curah,NaN,NaN,NaN,NaN
21,Pasar Sederhana,Daging Ayam Kampung,NaN,NaN,NaN,NaN
22,Pasar Sederhana,Telur Ayam Kampung,NaN,NaN,NaN,NaN
23,Pasar Sederhana,Susu Kental Manis Merk Bendera,NaN,NaN,NaN,NaN
24,Pasar Sederhana,Susu Kental Manis Merk Indomilk,NaN,NaN,NaN,NaN
25,Pasar Sederhana,Garam Beryodium Bata,NaN,NaN,NaN,NaN
26,Pasar Sederhana,Garam Beryodium Halus,NaN,NaN,NaN,NaN
27,Pasar Sederhana,Tepung Terigu Cakra Kembar,NaN,NaN,NaN,NaN
28,Pasar Sederhana,Tepung Terigu Kunci,NaN,NaN,NaN,NaN
29,Pasar Sederhana,Mie Instan,NaN,NaN,NaN,NaN
30,Pasar Sederhana,Cabe Rawit Hijau,NaN,NaN,NaN,NaN
31,Pasar Sederhana,Kacang Hijau,NaN,NaN,NaN,NaN
32,Pasar Sederhana,Susu Bubuk Dancow,NaN,NaN,NaN,NaN
33,Pasar Sederhana,Susu Bubuk Indomilk,NaN,NaN,NaN,NaN
34,Pasar Sederhana,Ikan Kembung,NaN,NaN,NaN,NaN

#### Slicing

In [28]:
(df.isnull().sum()!=33).to_list()

[True,
 True,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 False]

In [29]:
# Drop colums
df2 = df.loc[:, (df.isnull().sum()!=33).to_list()]

In [30]:
df2

,lokasi,nama_komoditas,2020-01-02,2020-01-03,2020-01-06,2020-01-07,2020-01-09,2020-01-10,2020-01-15,2020-01-16,2020-01-17,2020-01-21,2020-01-22,2020-01-23,2020-01-24,2020-01-27,2020-01-28,2020-01-30
0,Pasar Sederhana,Beras Medium,11000.0,11000.0,11000.0,11000.0,11000.0,11000.0,11000.0,11000.0,11000.0,11000.0,11000.0,11000.0,11000.0,11000.0,11000.0,11000.0
1,Pasar Sederhana,Cabe Merah,45000.0,45000.0,40000.0,40000.0,40000.0,60000.0,70000.0,70000.0,70000.0,80000.0,80000.0,80000.0,70000.0,70000.0,80000.0,80000.0
2,Pasar Sederhana,Bawang Merah,40000.0,35000.0,32000.0,40000.0,40000.0,40000.0,30000.0,30000.0,28000.0,30000.0,30000.0,30000.0,28000.0,28000.0,30000.0,30000.0
3,Pasar Sederhana,Daging Ayam Ras,35000.0,34000.0,34000.0,34000.0,34000.0,34000.0,38000.0,35000.0,34000.0,32000.0,32000.0,32000.0,32000.0,32000.0,32000.0,32000.0
4,Pasar Sederhana,Telur Ayam Ras,25000.0,25000.0,25000.0,24000.0,24000.0,24000.0,24000.0,24000.0,24000.0,24000.0,24000.0,24000.0,44000.0,24000.0,24000.0,24000.0
5,Pasar Sederhana,Daging Sapi,110000.0,110000.0,110000.0,110000.0,110000.0,110000.0,110000.0,110000.0,110000.0,110000.0,110000.0,110000.0,110000.0,110000.0,110000.0,110000.0
6,Pasar Sederhana,Minyak Goreng,14000.0,14000.0,14000.0,14000.0,14000.0,14000.0,14000.0,14000.0,14000.0,14000.0,14000.0,14000.0,14000.0,14000.0,14000.0,14000.0
7,Pasar Sederhana,Gula Pasir,13000.0,13000.0,13000.0,13000.0,13000.0,13000.0,13000.0,13000.0,13000.0,13500.0,13000.0,13000.0,13000.0,13000.0,13000.0,13000.0
8,Pasar Sederhana,Kentang,15000.0,15000.0,15000.0,15000.0,15000.0,15000.0,15000.0,15000.0,15000.0,18000.0,18000.0,18000.0,17000.0,17000.0,18000.0,18000.0
9,Pasar Sederhana,Kedelai,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0
10,Pasar Sederhana,Tepung Terigu,7500.0,7500.0,7500.0,7500.0,7500.0,7500.0,7500.0,7500.0,7500.0,7500.0,7500.0,7500.0,7500.0,7500.0,7500.0,7500.0
11,Pasar Sederhana,Bawang Putih,35000.0,NaN,32000.0,NaN,35000.0,40000.0,35000.0,35000.0,35000.0,35000.0,35000.0,35000.0,32000.0,32000.0,35000.0,35000.0
12,Pasar Sederhana,Cabe Keriting,48000.0,48000.0,50000.0,55000.0,55000.0,55000.0,55000.0,55000.0,60000.0,60000.0,60000.0,60000.0,50000.0,60000.0,60000.0,60000.0
13,Pasar Sederhana,Cabe Rawit,50000.0,40000.0,40000.0,60000.0,60000.0,60000.0,70000.0,70000.0,70000.0,100000.0,100000.0,100000.0,80000.0,80000.0,90000.0,90000.0
14,Pasar Sederhana,Kacang Tanah,30000.0,30000.0,26000.0,26000.0,26000.0,26000.0,26000.0,26000.0,30000.0,30000.0,30000.0,30000.0,30000.0,30000.0,30000.0,30000.0
15,Pasar Sederhana,Ubi Kayu,5000.0,5000.0,5000.0,5000.0,5000.0,5000.0,5000.0,5000.0,5000.0,5000.0,5000.0,5000.0,5000.0,5000.0,5000.0,5000.0
17,Pasar Sederhana,Jagung,12000.0,12000.0,12000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0
18,Pasar Sederhana,Ikan Olahan,80000.0,80000.0,80000.0,80000.0,80000.0,80000.0,80000.0,80000.0,80000.0,80000.0,80000.0,80000.0,80000.0,80000.0,80000.0,80000.0
20,Pasar Sederhana,Minyak Goreng Curah,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0,13000.0,13000.0,13000.0
21,Pasar Sederhana,Daging Ayam Kampung,75000.0,75000.0,75000.0,75000.0,75000.0,75000.0,75000.0,75000.0,75000.0,75000.0,75000.0,75000.0,75000.0,75000.0,75000.0,75000.0
22,Pasar Sederhana,Telur Ayam Kampung,44000.0,44000.0,44000.0,44000.0,44000.0,44000.0,44000.0,44000.0,44000.0,44000.0,44000.0,44000.0,44000.0,44000.0,44000.0,44000.0
23,Pasar Sederhana,Susu Kental Manis Merk Bendera,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0
24,Pasar Sederhana,Susu Kental Manis Merk Indomilk,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0
25,Pasar Sederhana,Garam Beryodium Bata,3500.0,3500.0,3500.0,3500.0,3500.0,3500.0,3500.0,3500.0,3500.0,3500.0,3500.0,3500.0,3500.0,3500.0,3500.0,3500.0
26,Pasar Sederhana,Garam Beryodium Halus,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0
27,Pasar Sederhana,Tepung Terigu Cakra Kembar,8000.0,8000.0,8000.0,13000.0,8000.0,8000.0,8000.0,8000.0,8000.0,8000.0,8000.0,8000.0,8000.0,8000.0,8000.0,8000.0
28,Pasar Sederhana,Tepung Terigu Kunci,7000.0,7000.0,7000.0,7000.0,7000.0,7000.0,8000.0,7000.0,7000.0,7000.0,7000.0,7000.0,7000.0,7000.0,7000.0,7000.0
29,Pasar Sederhana,Mie Instan,2500.0,2500.0,2500.0,2500.0,2500.0,2500.0,2500.0,2500.0,2500.0,2500.0,2500.0,2500.0,2500.0,2500.0,2500.0,2500.0
30,Pasar Sederhana,Cabe Rawit Hijau,35000.0,28000.0,28000.0,35000.0,35000.0,50000.0,35000.0,35000.0,30000.0,30000.0,30000.0,30000.0,36000.0,36000.0,36000.0,36000.0
31,Pasar Sederhana,Kacang Hijau,22000.0,22000.0,24000.0,24000.0,24000.0,24000.0,24000.0,24000.0,24000.0,24000.0,24000.0,24000.0,24000.0,24000.0,24000.0,24000.0
32,Pasar Sederhana,Susu Bubuk Dancow,43700.0,43700.0,43700.0,43700.0,43700.0,43700.0,43700.0,43700.0,43700.0,43700.0,43700.0,43700.0,43700.0,43700.0,43700.0,43700.0
33,Pasar Sederhana,Susu Bubuk Indomilk,36100.0,36100.0,36100.0,36100.0,36100.0,36100.0,36100.0,36100.0,10000.0,10000.0,36100.0,36100.0,36100.0,36100.0,36100.0,36100.0
34,Pasar Sederhana,Ikan Kembung,45000.0,45000.0,45000.0,45000.0,45000.0,45000.0,45000.0,45000.0,45000.0,45000.0,45000.0,45000.0,45000.0,45000.0,45000.0,45000.0

In [31]:
df2.shape

(33, 18)

### Memeriksa Missing Value Sisanya

In [32]:
df2.isnull().sum()

lokasi            0
nama_komoditas    0
2020-01-02        0
2020-01-03        1
2020-01-06        0
2020-01-07        1
2020-01-09        0
2020-01-10        0
2020-01-15        0
2020-01-16        0
2020-01-17        0
2020-01-21        0
2020-01-22        0
2020-01-23        0
2020-01-24        0
2020-01-27        0
2020-01-28        0
2020-01-30        0
dtype: int64

In [33]:
(df2.isnull().sum()).sum()

2

In [34]:
df2.iloc[:, [0, 1, 3, 5]]

             lokasi                   nama_komoditas  2020-01-03  2020-01-07
0   Pasar Sederhana                     Beras Medium     11000.0     11000.0
1   Pasar Sederhana                       Cabe Merah     45000.0     40000.0
2   Pasar Sederhana                     Bawang Merah     35000.0     40000.0
3   Pasar Sederhana                  Daging Ayam Ras     34000.0     34000.0
4   Pasar Sederhana                   Telur Ayam Ras     25000.0     24000.0
5   Pasar Sederhana                      Daging Sapi    110000.0    110000.0
6   Pasar Sederhana                    Minyak Goreng     14000.0     14000.0
7   Pasar Sederhana                       Gula Pasir     13000.0     13000.0
8   Pasar Sederhana                          Kentang     15000.0     15000.0
9   Pasar Sederhana                          Kedelai     12000.0     12000.0
10  Pasar Sederhana                    Tepung Terigu      7500.0      7500.0
11  Pasar Sederhana                     Bawang Putih         NaN         NaN
12  Pasar Sederhana                    Cabe Keriting     48000.0     55000.0
13  Pasar Sederhana                       Cabe Rawit     40000.0     60000.0
14  Pasar Sederhana                     Kacang Tanah     30000.0     26000.0
15  Pasar Sederhana                         Ubi Kayu      5000.0      5000.0
17  Pasar Sederhana                           Jagung     12000.0     10000.0
18  Pasar Sederhana                      Ikan Olahan     80000.0     80000.0
20  Pasar Sederhana              Minyak Goreng Curah     12000.0     12000.0
21  Pasar Sederhana              Daging Ayam Kampung     75000.0     75000.0
22  Pasar Sederhana               Telur Ayam Kampung     44000.0     44000.0
23  Pasar Sederhana   Susu Kental Manis Merk Bendera     10000.0     10000.0
24  Pasar Sederhana  Susu Kental Manis Merk Indomilk     10000.0     10000.0
25  Pasar Sederhana             Garam Beryodium Bata      3500.0      3500.0
26  Pasar Sederhana            Garam Beryodium Halus     12000.0     12000.0
27  Pasar Sederhana       Tepung Terigu Cakra Kembar      8000.0     13000.0
28  Pasar Sederhana              Tepung Terigu Kunci      7000.0      7000.0
29  Pasar Sederhana                       Mie Instan      2500.0      2500.0
30  Pasar Sederhana                 Cabe Rawit Hijau     28000.0     35000.0
31  Pasar Sederhana                     Kacang Hijau     22000.0     24000.0
32  Pasar Sederhana                Susu Bubuk Dancow     43700.0     43700.0
33  Pasar Sederhana              Susu Bubuk Indomilk     36100.0     36100.0
34  Pasar Sederhana                     Ikan Kembung     45000.0     45000.0

In [35]:
df2.iloc[[11]]

,lokasi,nama_komoditas,2020-01-02,2020-01-03,2020-01-06,2020-01-07,2020-01-09,2020-01-10,2020-01-15,2020-01-16,2020-01-17,2020-01-21,2020-01-22,2020-01-23,2020-01-24,2020-01-27,2020-01-28,2020-01-30
11,Pasar Sederhana,Bawang Putih,35000.0,NaN,32000.0,NaN,35000.0,40000.0,35000.0,35000.0,35000.0,35000.0,35000.0,35000.0,32000.0,32000.0,35000.0,35000.0

In [36]:
df2.iloc[[11]]

,lokasi,nama_komoditas,2020-01-02,2020-01-03,2020-01-06,2020-01-07,2020-01-09,2020-01-10,2020-01-15,2020-01-16,2020-01-17,2020-01-21,2020-01-22,2020-01-23,2020-01-24,2020-01-27,2020-01-28,2020-01-30
11,Pasar Sederhana,Bawang Putih,35000.0,NaN,32000.0,NaN,35000.0,40000.0,35000.0,35000.0,35000.0,35000.0,35000.0,35000.0,32000.0,32000.0,35000.0,35000.0

In [37]:
df2.iloc[11, [3, 5]]

2020-01-03    NaN
2020-01-07    NaN
Name: 11, dtype: object

In [ ]:
df2.iloc[[11]].median(axis = 1)

In [ ]:
df2.iloc[11, [3]] = df2.iloc[[11]].median(axis = 1)
df2.iloc[11, [5]] = df2.iloc[[11]].median(axis = 1)

In [ ]:
df2.iloc[[11]]

In [ ]:
df2.isnull().sum()

In [ ]:
df2

In [ ]:
df2.shape

## Menambah Kolom Kategori ke Dataset Menggunakan Merge Dataframe

In [ ]:
!dir

In [ ]:
df_kat = pd.read_csv("kategori-komoditas-pasar-sederhana.csv")

In [ ]:
df_kat

In [ ]:
df_kat.shape

In [ ]:
# Kategori column is in one dataset
df_kat['Kategori'].unique()

In [ ]:
df_kat['nama_komoditas'].groupby(df_kat['Kategori']).count()

In [ ]:
df_kat['nama_komoditas'].groupby(df_kat['Kategori']).value_counts()

In [ ]:
df_kat[['Kategori', 'nama_komoditas']]

In [ ]:
# Create new dataframe called Full Dataset
df_full = pd.merge(df2, df_kat[['Kategori', 'nama_komoditas']], on = 'nama_komoditas')

In [ ]:
df_full

In [ ]:
df_full.describe()

In [ ]:
df_full.shape

## Merapikan Dataset Baru

In [ ]:
list(df_full)

In [ ]:
df_full = df_full[['lokasi',
 'nama_komoditas',
 'Kategori',
 '2020-01-02',
 '2020-01-03',
 '2020-01-06',
 '2020-01-07',
 '2020-01-09',
 '2020-01-10',
 '2020-01-15',
 '2020-01-16',
 '2020-01-17',
 '2020-01-21',
 '2020-01-22',
 '2020-01-23',
 '2020-01-24',
 '2020-01-27',
 '2020-01-28',
 '2020-01-30']]

In [ ]:
# Change column name
df_full.rename(columns={'lokasi':'Lokasi'}, inplace=True)
df_full.rename(columns={'nama_komoditas':'Nama Komoditas'}, inplace=True)

In [ ]:
df_full.head()

In [ ]:
df_full.info()

## Membuat Data Tabular untuk Kategori

In [ ]:
df_full.groupby(df_full['Kategori']).mean()

In [ ]:
df_group_kat = df_full.groupby(df_full['Kategori']).mean()

In [ ]:
df_group_kat

In [ ]:
df_group_kat.shape

In [ ]:
# Transpose dataframe
df_tab_kat = df_group_kat.transpose(copy = True)

In [ ]:
df_tab_kat

In [ ]:
df_tab_kat.shape

In [ ]:
df_tab_kat.columns.name = ''
df_tab_kat.columns.name

In [ ]:
df_tab_kat.index.name = 'Tanggal'
df_tab_kat.index.name

In [ ]:
df_tab_kat

In [ ]:
df_tab_kat.info()

In [ ]:
df_tab_kat.describe()

In [ ]:
# Save dataset
df_tab_kat.to_csv('Data/west java jan 2020 commodities tabular dataset based on categories.csv', index = True)

## Membuat Line Plot dari Data Tabular untuk Kategori

In [ ]:
import matplotlib.pyplot as plt
plt.style.use('seaborn')
import seaborn as sns

In [ ]:
list(df_tab_kat)

In [ ]:
list(df_tab_kat.index)

In [ ]:
pd.Series(pd.to_datetime(df_tab_kat.index))

In [ ]:
pd.Series(pd.to_datetime(df_tab_kat.index)).dt.day

In [ ]:
pd.Series(pd.to_datetime(df_tab_kat.index)).dt.day.shape

In [ ]:
sns.lineplot(x = pd.Series(pd.to_datetime(df_tab_kat.index)).dt.day, y = df_tab_kat['Bumbu'].values, label = 'Bumbu')

In [ ]:
sns.lineplot(x = pd.Series(pd.to_datetime(df_tab_kat.index)).dt.day, y = df_tab_kat['Bumbu'].values, label = 'Bumbu')
sns.lineplot(x = pd.Series(pd.to_datetime(df_tab_kat.index)).dt.day, y = df_tab_kat['Karbohidrat'].values, label = 'Karbohidrat')
sns.lineplot(x = pd.Series(pd.to_datetime(df_tab_kat.index)).dt.day, y = df_tab_kat['Minuman'].values, label = 'Minuman')
sns.lineplot(x = pd.Series(pd.to_datetime(df_tab_kat.index)).dt.day, y = df_tab_kat['Minyak Memasak'].values, label = 'Minyak Memasak')
sns.lineplot(x = pd.Series(pd.to_datetime(df_tab_kat.index)).dt.day, y = df_tab_kat['Protein'].values, label = 'Protein')
plt.ylim((0,75000))
plt.legend()
plt.show();

In [ ]:
df_kat['nama_komoditas'].groupby(df_kat['Kategori']).value_counts()